move_group:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        joint_1:
          has_velocity_limits: true
          max_velocity: 0.4031710572106901
          has_acceleration_limits: false
          max_acceleration: 0
        joint_2:
          has_velocity_limits: true
          max_velocity:  0.3921754829231258
          has_acceleration_limits: false
          max_acceleration: 0
        joint_3:
          has_velocity_limits: true
          max_velocity: 0.7257079029792421
          has_acceleration_limits: false
          max_acceleration: 0
        joint_4:
          has_velocity_limits: true
          max_velocity: 0.7391469382195985
          has_acceleration_limits: false
          max_acceleration: 0
        joint_5:
          has_velocity_limits: true
          max_velocity: 0.7391469382195985
          has_acceleration_limits: false
          max_acceleration: 0
        joint_6:
          has_velocity_limits: true
          max_velocity: 1.1093312725675959
          has_acceleration_limits: false
          max_acceleration: 0
